### ISSUE TITLE
Create logic that handles the event where the selected provider does not respond

### ISSUE THREAD

**Issue by forgetso** [prosopo/procaptcha#61]
A user receives a random provider from the contract. If the selected fails to respond, the captcha component should automatically retrieve a new random provider and use it instead.

**Comment by forgetso** [comment]
For the provider not responding bug you can register loads of providers in the smart contract that are not running API endpoints. Register them in [polkadot /apps interface](https://polkadot.js.org/apps/) and have, for example, 1 provider running an API and 9 defunct providers. The mechanism should request random providers until the active one is set or until a limit is reached. There's no point in continuing to try to randomly select a provider if we've waited too long already. The limit should be configurable.

A follow up to this is provider health monitoring in the protocol smart contract:

- [ ] monitor if providers are active and update a smart contract function, deactivating unresponsive providers
- [ ] FUTURE monitor if providers are active from the prosopo parachain nodes

**Comment by goastler** [comment]
Should the limit be a number of providers or a time limit or both?

Should there be a threshold of the number of providers available? If the number of providers dips below this threshold, then there may be too few nodes to randomly pick from. E.g. the randomisation aspect isn't great if there's only 2 providers. It would probably be better to flag that the network doesn't have enough providers to carry out the captcha challenge.

**Comment by goastler** [comment]
After some discussion, this will be prevented by reselecting a provider on the next block if they do not respond. This will be done `n` times until a responding provider is found, else an error message will be displayed.

To reduce the likelihood of this happening, providers' stakes will be slashed for being offline at these times to decentivise this situation.
